name = "uTEBD"
uuid = "d860ffec-cfcf-436b-bdd3-09fa5ad7387b"
version = "0.1.0"
authors = ["Christian MPB <christianhjoh@gmail.com>"]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Arpack = "0.5.4"
CUDA = "5.9.5"
ITensorMPS = "0.3.25"
ITensors = "0.9.15"
LinearAlgebra = "1.12.0"
Measures = "0.3.3"
Metal = "1.9.1"
ProgressMeter = "1.11.0"
Suppressor = "0.2.8"
Test = "1.11.0"
